### ISSUE TITLE
VisibleForTesting example please

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#10]
I'm trying to use @VisibleForTesting, so I annotate a private/internal method with it, but do not get public access to it. Surely I must be doing something wrong because I'm not sure how to use it properly. Many thanks!

**Comment by peichhorn** [comment]
This is how it is supposed to work:
You relax the visibility of a method or a type as much as you need to access them in tests and annotate them with @VisibleForTesting. Now in Eclipse you will only be able to access these methods and types from classes whose names contain 'Test'. In Javac the methods and types will just be declared as private, so you can't use @VisibleForTesting in Netbeans. Since I usually work with eclipse and compile with javac (via ant or maven..) I chose to design the behaviour this way.

So @VisibleForTesting isn't all that great, well it works for me. If you got any ideas to improve it, I'm all ears.

**Comment by nicholas22** [comment]
I'm using Eclipse and creating an instance method e.g.:
  @VisibleForTesting
  void test123() { // package access level
  }

From a different package in a class called SomethingTest I attempt to access via an instance, e.g.:

new MyClass().test123();

but I'm getting an error that the method is not visible. I thought that this would work...?

**Comment by peichhorn** [comment]
Thats not how it work, sorry if I was unclear about it.
You have to make the method `test123()`  visible, so that the Test can access it. In all the other non-test classes you wont be able to access `test123()` since @VisibleForTesting virtually reduces the set visiblity to `private`.

**Comment by nicholas22** [comment]
Oh I see, thanks for the clarification.

**Comment by stephanenicolas** [comment]
Is it supposed to work with maven as well ? I get the error : "has private access in <classUnderTest>". I can't invoke the method annotated with @VisibleForTesting during the testCompile phase of maven.

Here is the exerpt from my pom.xml file : 

``` xml
<dependency>
            <groupId>com.github.peichhorn</groupId>
            <artifactId>lombok-pg</artifactId>
            <version>0.11.0</version>
            <scope>provided</scope>
        </dependency>
```

``` xml
<build>
        <sourceDirectory>src/main/java</sourceDirectory>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessors>
                        <annotationProcessor>lombok.core.AnnotationProcessor</annotationProcessor>
                    </annotationProcessors>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

Btw, artifact of 0.11.3 seems to have a bad signature on maven central.
