### ISSUE TITLE
Define the initialized fields in the @Builder.Extension annotation

### ISSUE THREAD

**Issue by lgathy** [peichhorn/lombok-pg#103]
Due to the change in version 0.11.2 it is no longer possible to create multiple builder extension methods for the same field with different method names. However this could be very useful if you want to initialize the same field using different input arguments. In case of an Iterator, it is useful to have one using an Iterable too, and to avoid disambigous calls, it is safer to name them differently:

``` java
@Builder.Extension
private void withPersonIterator(Iterator<Person> personIterator) { ... }

@Builder.Extension
private void withPersons(Iterable<Person> persons) { ... }
```

Since the initialized fields are determined from the method name, the second extension will be invalid. Since this behaviour is a really good for most cases, it would make it an excellent default. But with a fields String array argument in the @Builder.Extension annotation a custom list of fields could be provided... like this:

``` java
@Builder.Extension(fields = "personIterator")
private void withPersons(Iterable<Person> persons) { ... }
```

I took a quick look into the code, and it does not seem to be a hard work. Only the Builder.Extension instance needs to be propagated to BuilderAndExtensionHandler.handleExtension(...) and then further to .getExtensionType(...) and .extensionFieldNames(...) where annotation.fields() should be returned if it is specified.

**Comment by peichhorn** [comment]
I'm sorry for the regression.
Thanks for the detailed report and the decent suggestion. I will do exactly that.

Now the reason for the regression:

As you may know, `@Builder` uses some interface wizardry to guarantee that required fields are initialized.
The issue with `@Builder.Extension` is, that we need to decide if the extension initializes required fields or not.
And if it initializes required fields, we need to make sure that it initializes all required fields.
Prior to 0.11.2 `@Builder.Extension` was smart enough to figure this out, by looking at the assignments in the method body of the extension. This was how I envisioned `@Builder.Extension` from the start and is still pretty much the only way I'm happy with `@Builder.Extension`, since there was not need to configure anything.
However in certain cases eclipse doesn't have the content of the annotated method, since eclipse parses the source files in diet-mode sometimes. This means from a technical viewpoint, classifying `@Builder.Extension` correctly is not possible in eclipse, and only in eclipse.

Therefore I've had to think of an alternative way to identify the fields that an extension touches.
And as you've experienced first hand, I've thought of the worst way to do it. I'm sorry once again.

**Comment by peichhorn** [comment]
Done, I will probably release a new snapshot release tomorrow.
