### ISSUE TITLE
@BoundSetter ignored when @Data used

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#116]
It would appear in 0.11.4-SNAPSHOT that using @Data will result in @BoundSetter being ignored. I would have expected @BoundSetter to have precedence - both at class level and individual property level.

Also, I've noticed that delombok isn't converting @BoundSetter annotations even when it the binary is being converted. Is that just a minor oversight?

**Comment by peichhorn** [comment]
The issue is, that technically `@Data` is being processed first. Therefore when handling `@Data` we need check if there are other annotations present on the type or the fields, that may generate setters as well. I know that I've patched this part of lombok once to work with lombok-pg's `@FluentSetter`, `@BoundSetter` and `@LazyGetter`. I'm pretty sure there was an internal change in lombok, that I've missed.
So I'm going to have to fix it again... :/

(It would be great if lombok could prioritize handlers.. maybe this is what I will work on to fix this issue..)

**Comment by peichhorn** [comment]
Browsing through the history of some classes it looks like this didn't work for a long long time.. -.-
