### ISSUE TITLE
@Function and @Validate combo bug

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#17]
Using @Validate and @Function on a method gives you a compiler warning: duplicate @SuppressWarnings annotation. Hopefully they can be made to detect when this annotation has already been emitted and avoid doing so in this case.

**Comment by peichhorn** [comment]
Since all other lombok-pg method-level annotations implicitly trigger the parameter validation (same thing @Validate does), I just need to introduce this behavior for @Function and @Action. 
@Validate and @Sanitize are meant for all the methods not annotated with lombok-pg stuff at all.
But to guarantee that methods will only get one @SuppressWarnings("all") is the list as well.

**Comment by nicholas22** [comment]
So you mean that all lombok-pg annotations do a @Validate and @NotNull on all arguments by default?

**Comment by peichhorn** [comment]
@Validate just tells lombok-pg to look at the parameter annotations, so if it finds @Validate.NotNull it will create a null check for that parameter. Now @DoPrivileged and all the other method-level annotations will also tell lombok-pg to look at the parameter annotations. But I forgot to do the same think with @Function and @Action. Quick example:

```
// not need since @Function already triggers the parameter validation and sanitation 
// @Validate
@Function
public Boolean foo(@Validate.NotEmpty String a, @Validate.NotEmpty @Sanitize.Normalize String b) {
  return a.matches(b);
}
```

(sorry, I really need to work on my explanatory skills)

**Comment by nicholas22** [comment]
Oh OK gotcha, no problem then, so once that's done let's close this one. I'll put this in the documentation. Don't forget to create the placeholders (html files) for me to edit!
