### ISSUE TITLE
Data(callSuper=true/false)

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#4]
In many instances when dealing with class inheritance, there is boilerplate in lombok annotations, because the &#64;Data annotation cannot be used. The reason for this is that it does not allow for equals, hashcode and toString to specify whether to call super implementations of these methods or not. So end users have to use @Data in a superclass, then for any subclasses they have to use &#64;EqualsAndHashcode and &#64;ToString, with appropriate callSuper=T/F configuration.

It would be nice to be able in one go to say whether super should be called or not e.g. &#64;Data(callSuper=true). This would create the relevant equals, hashcode and toString with this property set to the appropriate boolean value. 

I don't think there is a need for super-fine-grained control here, e.g. callSuperEquals and callSuperToString, because the subclass would typically behave uniformly in this respect.

**Comment by peichhorn** [comment]
I would even say, that @Data(callSuper=true) should generate constructors that call the appropriate super-constructor.
So lets say the superclass has a no argument constructor and a two argument constructor, while the subclass, annotated with @Data has three required fields. Now @Data should generate 2 Constructors in the subclass one that takes 3 arguments and calls super() and the other one that takes 5 arguments and calls super(arg1, arg2).

And callSuper=true really should be the default

**Comment by nicholas22** [comment]
I would welcome this, although calling the default super constructor would be more than enough for most of my use-cases, because any special invocations can be implemented as required. The aim for me is to stick to just using the @Data annotation, rather than having to use the other ones too, when developing POJOs. It makes it easier to grasp for other developers.

**Comment by nicholas22** [comment]
bump!

**Comment by peichhorn** [comment]
Just updated the [lombok-pg-0.10.0.jar](http://cloud.github.com/downloads/peichhorn/lombok-pg/lombok-pg-0.10.0.jar), which supports @Data(callSuper=true). The default value is false, because this is the default value for both @ToString and @EqualsAndHashCode.
For now @Data(callSuper=true) only affects @ToString and @EqualsAndHashCode. I will add support for @XXXConstructor later.
Furthermore this feature request will probably go into lombok once I have time to add some tests since it is listed as [issue 19](http://code.google.com/p/projectlombok/issues/detail?id=19).

Please verify that is works and close the issue if it does, thx

**Comment by nicholas22** [comment]
It appears to work fine on my machine, I will run it for a day or two at work where I have much more code that uses this as well as a very robust JUnit harness, to see if there are any issues. I'll make sure to close this when that's done. Many thanks for this!

**Comment by nicholas22** [comment]
Works without a hitch ;)
