### ISSUE TITLE
@ExtensionMethod and type-parameter

### ISSUE THREAD

**Issue by peichhorn** [peichhorn/lombok-pg#5]
For now this does not work, which is pretty sad:

```
@ExtensionMethod(Objects.class)
class Test {
  void test() {
    String s = getFoo().orElse("anotherValue");
  }
}

class Objects {
  public static <T> T orElse(T value, T orElse) {
    return value == null ? orElse : value;
  }
}
```

**Comment by nicholas22** [comment]
Ah, this is so similar to Option&lt;T&gt; of Scala... Yes it would be a nice addition to this fantastic library!

**Comment by nicholas22** [comment]
Isn't this going to work if you substitute T with Object?

**Comment by nicholas22** [comment]
I realise now that if you substitute every T with Object in the Objects class, you then have to downcast to use orElse(), which is a bit of a pain...

**Comment by nicholas22** [comment]
However, this workaround will work for any class type. There is the obvious risk of a CCE, but the context _should_ make things obvious. You still need to downcast...

class Objects {
&nbsp;&nbsp;&nbsp;@SuppressWarnings("unchecked")
&nbsp;&nbsp;&nbsp;public static &lt;T&gt; T orElse(Object value, T orElse) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return value == null ? orElse : (T)value;
&nbsp;&nbsp;&nbsp;}
}

It may be a problem trying to resolve this issue, due to type erasure. You can't unfortunately do a T.getClass() as in C#, for obvious reasons. In my library I have used a SuperTypeToken approach. I'm not entirely convinced this is the best way but sometimes you _REALLY_ need T.getClass()... source:https://github.com/nicholas22/jpropel/blob/master/src/propel/core/utils/SuperTypeToken.java 

Example: 
class MyClass&lt;T&gt; {
&nbsp;&nbsp;&nbsp;public void test() {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.out.println(SuperTypeToken.getClazz(this.getClass()));
&nbsp;&nbsp;&nbsp;}
}

For this to work, MyClass should be initialised like this: new MyClass&lt;String&gt;() { }.test(); // prints "String", note: brackets.

<B>Edit<B>: Having a closer look at this, it seems that lombok can't infer the type, although in similar circumstances the compiler does so. So erasure would not be a problem. Which is good news.

**Comment by peichhorn** [comment]
For now these workarounds might be alright, but I really need to add proper support for type-parameters.

**Comment by nicholas22** [comment]
Looking at the decompiled version of a vanilla/statically called Objects.orElse(null, "test"), I see that the compiler has added an explicit cast, e.g.:

String name=null;
String s = (String)Objects.orElse(name, "123"); // String cast inserted by compiler!

Perhaps you could do this as well upon encountering a generic type (e.g. T, G, etc.) especially since you have the know-how of implementing the 'val' keyword, which basically detects the compile-time type if I understand correctly. Would it be possible to re-use that? That way, we wouldn't get the type mismatch error...

**Comment by peichhorn** [comment]
Yeah the internals of 'val' should be a good starting point to fix this.

**Comment by peichhorn** [comment]
Quick update:

@ExtensionMethod works with 

```
public static <T> T orElse(final T value, final T orElse) {
  return value == null ? orElse : value;
}
```

What's left to do:
- Support stuff like `T[]`, `List<T>`, `Iterable<T>`

```
public static <T> Iterable<T> filter(final Iterable<T> list, final Function1<T, Boolean> filter) {
  for (T element : list) if (filter.apply(element)) yield(element);
}

public static <S, T> Iterable<T> map(final Iterable<S> list, final Function1<S, T> mapping) {
  for (S element : list) yield(mapping.apply(element));
}
```

(`@ExtensionMethod`, `@Function` and `Yield.yield(...)` work so well with one another. I like it)
- auto-complete breaks code, example:

```
User user = connectedUser().<CURSOR>; // try to add orElse here
return user.getCharacter();
```

results in:

```
User user = connectedUser().orElse(arg0)rn user.getCharacter();
```

(I think I've just used the wrong method to calculate the length of the completion snippet)

**Comment by nicholas22** [comment]
This is great stuff :)
Let me play around a bit today/tomorrow...

**Comment by nicholas22** [comment]
I tried the first example and I'm getting: 

Exception in thread "main" java.lang.VerifyError: (class: main/Main, method: main signature: ([Ljava/lang/String;)V) Incompatible argument to function
Could not find the main class: main.Main.  Program will exit.

I'm just doing this:

@ExtensionMethod(Objects.class)
public class Main
{
&nbsp;&nbsp;&nbsp;public static void main(String[] args)
&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String name = null;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;System.out.println(name.orElse("123"));
&nbsp;&nbsp;&nbsp;}
}

with 

public class Objects
{
&nbsp;&nbsp;&nbsp;public static &lt;T&gt; T orElse(final T value, final T orElse)
&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return value == null ? orElse : value;
&nbsp;&nbsp;&nbsp;}
}

...at least is compiles! :)

**Comment by peichhorn** [comment]
I get the same error. The fun fact is, that decompiled the class looks OK.

Update:
this works:

```
String name = null;
name = (name.orElse("123");
System.out.println(name);
```

I look into it, can't be that hard.

**Comment by nicholas22** [comment]
Hahahahaha very funny indeed! That's software right?

...Just a thought, the verifier maintains a pre-compiled symbols table so
maybe you are changing something that it is looking for?

**Comment by peichhorn** [comment]
I just ran the code with netbeans and it works, so it's only the eclipse part, that is messed up. Yay only half the work.

**Comment by nicholas22** [comment]
OK please see if you can fix it, as we both use eclipse xD

**Comment by peichhorn** [comment]
@ExtensionMethod finally works as advertised, so enjoy

(updated the lombok-0.10.0.jar and made sure that the upload was compete this time xD)

**Comment by nicholas22** [comment]
Thanks that's great!
