### ISSUE TITLE
Ivy repo doesn't work

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#56]
Referencing the Ivy repo produces an error: 

Impossible to resolve dependencies of ...
unresolved dependency: com.github.peichhorn#lombok-pg;0.10.4-SNAPSHOT: not found

Produced when adding the following dependency:
&lt;dependency org="com.github.peichhorn" name="lombok-pg" rev="0.10.4-SNAPSHOT" /&gt;

**Comment by peichhorn** [comment]
Make sure you use this pattern in you repo definition

```
[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]
```

NB: Should probably document this :/

**Comment by peichhorn** [comment]
I'm not sure that the runtime artifact gets resolved in Ivy. I will try this out tonight and maybe change the name (or artifactId for the maven folks) to `lombok-pg-runtime`.

**Comment by nicholas22** [comment]
how do I use the artifact pattern you specified above in Ivy?

**Comment by nicholas22** [comment]
I found out how but it still doesn't work :/

**Comment by nicholas22** [comment]
Searching for lombok in Maven Central only returns the plain lombok as well (and an intellij plugin) but no lombok-pg

**Comment by peichhorn** [comment]
> Searching for lombok in Maven Central only returns the plain lombok...

Um yeah I haven't released lombok-pg 0.10.4 yet. And only the releases will be on central after an auto-sync.
For now you should stick to these repos:

Snapshots: https://oss.sonatype.org/content/repositories/snapshots/
Releases: https://oss.sonatype.org/content/repositories/releases/

I let you know when the artifact is available on central (may take 1-2 days the first time, since I have to explicitly request auto-sync to central)

**Comment by peichhorn** [comment]
This resolves everything properly:

```
<dependency org="com.github.peichhorn" name="lombok-pg" rev="0.10.4-SNAPSHOT" changing="true" />
```

```
<ibiblio name="sonatype-snapshots" m2compatible="true" usepoms="true" pattern="[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]" root="https://oss.sonatype.org/content/repositories/snapshots/"/>
```

But I have to distribute the runtime artifact under a separate artifactId. I let you know when it works.. (and of cause I will update the documentation)

**Comment by nicholas22** [comment]
OK I will use a local dependency for now and update when this stuff becomes a bit more stable. Please see if you can make it work as transparently as possible in the long run (even without the pattern) as this would be of great help to users.

**Comment by peichhorn** [comment]
I will figure something out (till tomorrow) and provide a more detailed example configuration for Ivy.

**Comment by peichhorn** [comment]
Tested it with both maven and ivy.. it works.. I fixed the documentation and added  a example configuration.
Btw, the trick was not to replace SNAPSHOT with a timestamps. Who knew? xD

**Comment by nicholas22** [comment]
Thanks dude

**Comment by nicholas22** [comment]
Please initiate the process for the release repo if and when you can, as one of the requirements to being accepted is to be dependent on libs that are on release stage also ;0

**Comment by peichhorn** [comment]
Sure thing, I'm just hunting down a javac bug of @EnumId that I found at my last testing session, before releasing the staged version. If I'm unable to solve this issue in 1-2 hours I will release 0.10.4 either way. And submit the sync-request shortly after.

Just so you know what nature this bug is, when compiling with javac I get a 'error: illegal forward reference' and I'm pretty sure the reason for this error are messed up position infos.
