### ISSUE TITLE
@Validate not working on constructors with only a constructor call.

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#60]
I am not able to annotate @Validate.NotNull on a constructor which calls super, in Eclipse. I get an error message: can only be applied to concrete methods. It works if the constructor doesn't call super.

**Comment by peichhorn** [comment]
Just fixed it.
I forgot that in the eclipse AST a constructor call (super(...) or this(...)) is not treated as a statement of the method body.

**Comment by nicholas22** [comment]
Works on eclipse, doesn't work on javac.

**Comment by peichhorn** [comment]
Yeah, sadly I forgot to handle the this(...) construtor call in javac. This has been fixed now. Constructors with a super() call should have worked all along. I've added a test scenario and did some manual testing in netbeans.

Please verify that the issue is solved and close this issue.
(new edge release: 0.10.5-SNAPSHOT)

**Comment by nicholas22** [comment]
Thanks
