### ISSUE TITLE
@Builder.Extension

### ISSUE THREAD

**Issue by rvakkada** [peichhorn/lombok-pg#73]
The example provided in Builder.Extension method withIdAndText are not really visible. I am not sure how they have to be used as the Builder.Example.$TextRef returns an instance of the builder already and there is not visiblity to call withIdAndText. Can you thorw some light.

Also is it possible to make the $Builder public so that we can use those builder to build all final classes at once

**Comment by peichhorn** [comment]
With the annotation `@Builder.Extension` you mark a method, that you want to be part of the Builder. Though the method itself will not be part of the Class annotated with `@Builder` thats why I chose the private access modifier.

As for the example:

The interface `$TextDef` defines a method `$OptionalDef idAndText(String id, String text)` matching the signature of the builder extension. And since `$TextDef` is visible, so is the method.

`BuilderExtensions.builderExtensions().withIdAndText("42", "some text").build()`

**Comment by peichhorn** [comment]
> Also is it possible to make the $Builder public so that we can use those builder to build all final classes at once

Possible of cause, but it does not make much sense. The idea of this Builder concept is, that the `$Builder` contains all the different methods to set the field values, while the different interfaces forces the user to specify values for the mandatory fields and allow him do specify optional values.
Another basic idea of this concept is that one should only able to specify one value per method call. Builder extensions are the exception here of cause.

If I were to add a mechanism that would allow one to specify all mandatory fields in one go, than one would end up with 5 or more argument methods really fast. Which would make the Builder kind of obsolete.

As for know, just define a builder extension. I need to think about this a bit longer. ;)

**Comment by rvakkada** [comment]
Is it possible to remove the $ in the buider classes and Interfaces.

-----Original Message-----

**Comment by rvakkada** [comment]
Though the extension methods are available in the eclipse outline view. But they are not recognized by eclipse ecitor

**Comment by peichhorn** [comment]
Sadly this is a bug. I'm working on it.

**Comment by peichhorn** [comment]
> Is it possible to remove the $ in the builder classes and Interfaces.

Although I've intended not to allow the user to hold references to generated interfaces, I think you're right,
I should remove the $ from the interface names, since the awkward type name does not necessarily keep
the user from holding references. The awkward name merely signaled that is was discouraged.

**Comment by rvakkada** [comment]
Thanks for the prompt replies

----- Original Message -----
