### ISSUE TITLE
Version 0.10.8 not available through maven

### ISSUE THREAD

**Issue by ggtools** [peichhorn/lombok-pg#77]
Unless I missed something the only version available on the maven repositories is 0.10.4. Shouldn't version 0.10.8 available as well ?

**Comment by peichhorn** [comment]
No, you didn't miss anything. There is a SNAPSHOT release of 0.10.8 available at
https://oss.sonatype.org/content/repositories/snapshots/ .
Since I made little progress during the time lombok 0.10.8 was released I'm skipping the 0.10.8 release in favor of 0.11.0 to keep up with the lombok version. I plan on releasing lombok-pg 0.11.0 this weekend.
