### ISSUE TITLE
SneakyThrows in constructor

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#83]
Seems that calling a constructor from another constructor in the same object prevents SneakyThrows from working properly:

``` java
    @Validate
    @SneakyThrows
    public CcyNetPosition(@NotNull final LocalDate date, @NotNull final AtomicDecimal net, @NotNull final LBMSDMRawTimestamp rxTimestamp)
    {
      this(date, net, rxTimestamp, new LBMSDMRawTimestamp(NetPosConstants.LBM_NOW));
    }
```

The LBMSDMRawTimestamp object uses a checked exception in its constructor which I'm trying to sneak past. 
Workaround: Use private static factory method local to this object...

**Comment by peichhorn** [comment]
I'm pretty sure that `@SneakyThrows` doesn't work for explicit constructor calls, since it surrounds the method body with
a try-catch-block and explicit constructor calls have to be the first statement in a constructor. I don't think there is anything we can do to make it work. Nonetheless I will look into it

**Comment by nicholas22** [comment]
Thanks mate- much appreciated. The workaround is simple enough so not a major blocker or anything.

**Comment by peichhorn** [comment]
As explained in my first comment, there is nothing we can do about it, sorry.
