### ISSUE TITLE
Documentation for @BoundPropertySupport/@BoundSetter

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#93]
I'd like to use the above-named annotations, but I don't know what they do.

Incidentally, if it is the same as @BindableData from LomProp then all is good with the world (do you have an equivalent "super" annotation to promote a @Data to a bound source?)

http://code.google.com/p/lomprop/

**Comment by peichhorn** [comment]
Yeah the documentation of this project is extremely bad. I see what I can do to change that.
`@BoundPropertySupport` should be pretty much the same as `@BindableData`

There is actually a small example in the wiki, where I will update the project documentation: [link](https://github.com/peichhorn/lombok-pg/wiki/%40BoundPropertySupport-%40BoundSetter)

**Comment by fommil** [comment]
Thanks Philipp,

By the way, is your project supposed to sit beside Lombok or a replacement? Because many classes are the same, Lombok-pg breaks my builds (mostly @Cleanup changes in behaviour). And if the latter, how aligned are the sources? (ie do you incorporate Lombok bug fixes and updates?)

**Comment by peichhorn** [comment]
You shouldn't mix lombok and lombok-pg because I've modified `@Cleanup` to work with `yield` and `@Data` to have `callSuper=true`. The installation process into eclipse is also easier with just one jar.

> Lombok-pg breaks my builds (mostly @Cleanup changes in behaviour)

Do a search-replace and change `@Cleanup` to `@Cleanup("close")` (which btw also works for lombok)

> And if the latter, how aligned are the sources? (ie do you incorporate Lombok bug fixes and updates?

I perform frequent updates and usually work against to lombok HEAD.

**Comment by fommil** [comment]
OK, thanks for the explanation.

I'll add the parameter to @Cleanup, I'm not so sure I like that change from the canonical defaults. Why can't you use "close" as default and let the yielder's change the parameter?

I look forward to the implementation of "quiet close", as I see little reason to throw an IOException from a failed close operation (although I would like to log such cases, if possible).

Also - is there any chance of making @Cleanup work when applied to a method parameter?

## 

Sam

**Comment by peichhorn** [comment]
> I'm not so sure I like that change from the canonical defaults. Why can't you use "close" as default and let the yielder's change the parameter?

And that is a reasonable reaction, that I can fully understand.

Here are a few more details, to understand why I changed the behavior of `@Cleanup`:

If you use `@Cleanup` now, you get code like this:

``` java
Object annotatedVariable = //...
try {
  // something
} finally {
   if (annotatedVariable instanceof Closeable) {
     ((Closeable) in).close();
   }
}
```

This is about the only way I can make `@Cleanup` work together with `yield`, since `yield` returns either an `Iterator` or an `Iterable` and none of these interfaces define a `close` method.

But if you explicitly define a method, that should clean up the resources, you tell lombok not to assume, that the annotatedObject might be `Closeable` and therefore generate the usual code you know and love.

If you have a better idea how to get `@Cleanup` working with `yield`, without any regressions or incompatibilities for lombok users, please let me know.

> Also - is there any chance of making @Cleanup work when applied to a method parameter?

Sure why not, just create another feature request.

**Comment by fommil** [comment]
Hi Philipp,

I am a little confused by the problem. Indeed, I do not see why there is a problem.

Until now, I thought you were meaning Thread.yield, but that cannot be the case as it does not return anything. What do you mean by yield?

Also, why can't the @Cleanup annotation take a value, which is "close" by default? That way, if you want to call something else, then it can be the parameter.

## 

Sam

**Comment by fommil** [comment]
BTW, I just found the documentation for this annotation in the wiki! So I'm marking the issue as closed.

I suggest you remove the website http://peichhorn.github.com/lombok-pg/ as the documentation appears to be at https://github.com/peichhorn/lombok-pg/wiki

(I presume this is like the old sourceforge problem where projects tend to have homepages, websites and documentation pages - all of which are different. I had hoped the modern hosting solutions, like github, would have fixed this. At least it's not as bad as java.net's infinity of project pages!)

**Comment by fommil** [comment]
Argh, there appears to be some inconsistencies between the two documentation home pages. For example, yield is not documented on the wiki

 https://github.com/peichhorn/lombok-pg/wiki/Yield

but appears in this "homepage" of sorts

 http://peichhorn.github.com/lombok-pg/Yield.html

**Comment by peichhorn** [comment]
Yeah I'm currently moving everything to the wiki.. afterwards a redirect should guide everyone to the wiki..
